### ISSUE TITLE
Crashing when postgresql closes connection or timeout

### ISSUE THREAD

**Issue by henriquechehad** [nuveo/prest#126]
When postgresql stop with timeout or error like `DatabaseError: server closed the connection unexpectedly` pREST is crashing too.

Log:
```
runtime stack:
runtime.throw(0x948e50, 0x16)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc450af0000, 0x100000, 0x0, 0xbe2f18)
	/usr/local/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0xbc9bc0, 0x100000, 0x0)
	/usr/local/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0xbc9bc0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0xbc9bc0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0xbc9bc0, 0x1, 0x7f000000001f, 0x410cdb)
	/usr/local/go/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0x7fe643234888)
	/usr/local/go/src/runtime/asm_amd64.s:314 +0xab
runtime.(*mheap).alloc(0xbc9bc0, 0x1, 0x1000000001f, 0x40e7b9)
	/usr/local/go/src/runtime/mheap.go:580 +0xa0
runtime.(*mcentral).grow(0xbcbc20, 0x0)
	/usr/local/go/src/runtime/mcentral.go:210 +0x94
runtime.(*mcentral).cacheSpan(0xbcbc20, 0xc420017228)
	/usr/local/go/src/runtime/mcentral.go:91 +0xfa
runtime.(*mcache).refill(0x7fe6432c1000, 0xc40000001f, 0xc42006ae00)
	/usr/local/go/src/runtime/mcache.go:121 +0xae
runtime.(*mcache).nextFree.func1()
	/usr/local/go/src/runtime/malloc.go:505 +0x33
runtime.systemstack(0xc420016000)
	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079
```

```
goroutine 184133 [IO wait]:
net.runtime_pollWait(0x7fe6426fe738, 0x72, 0xc6)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4344d1bf0, 0x72, 0xc4205b4a00, 0xc42000c160)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4344d1bf0, 0xb99d40, 0xc42000c160)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4344d1b90, 0xc44a826000, 0x1000, 0x1000, 0x0, 0xb99d40, 0xc42000c160)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc449dcaff8, 0xc44a826000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc449239c20)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc449239c20, 0xc44a935360, 0x5, 0x200, 0x2, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0xb96ac0, 0xc449239c20, 0xc44a935360, 0x5, 0x200, 0x5, 0xc4206a0500, 0x20, 0x8)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0xb96ac0, 0xc449239c20, 0xc44a935360, 0x5, 0x200, 0x410e0f, 0xc4205b4c50, 0xc4201c5400)
	/usr/local/go/src/io/io.go:325 +0x58
shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq.(*conn).recvMessage(0xc44a935340, 0xc4206a0500, 0x88fe40, 0x1, 0xbe0ee8)
	/go/src/shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq/conn.go:957 +0x117
shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq.(*conn).recv1Buf(0xc44a935340, 0xc4206a0500, 0xc4205b4cd8)
	/go/src/shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq/conn.go:1007 +0x39
shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq.(*conn).recv1(0xc44a935340, 0x630dca, 0xc449dcaff8)
	/go/src/shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq/conn.go:1028 +0x87
shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq.(*conn).readParseResponse(0xc44a935340)
	/go/src/shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq/conn.go:1574 +0x2f
shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq.(*conn).prepareTo(0xc44a935340, 0xc450ad25f0, 0x4a, 0xc450ac5e10, 0x5, 0x4a)
	/go/src/shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq/conn.go:784 +0x63c
shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq.(*conn).Prepare(0xc44a935340, 0xc450ad25f0, 0x4a, 0x0, 0x0, 0x0, 0x0)
	/go/src/shelfgit.com/filmow/filmow-api/vendor/github.com/lib/pq/conn.go:804 +0x11f
database/sql.(*driverConn).prepareLocked(0xc4481843f0, 0xc450ad25f0, 0x4a, 0x0, 0x0, 0x411904, 0x7fe6413628e2)
	/usr/local/go/src/database/sql/sql.go:301 +0x55
database/sql.(*DB).prepare(0xc42010bd90, 0xc450ad25f0, 0x4a, 0xc4205b4f01, 0xc4201c5400, 0x450560, 0xc4201c5400)
	/usr/local/go/src/database/sql/sql.go:987 +0xa5
database/sql.(*DB).Prepare(0xc42010bd90, 0xc450ad25f0, 0x4a, 0xc4205b5080, 0x410ead, 0xc4507d5b88)
	/usr/local/go/src/database/sql/sql.go:964 +0x60
shelfgit.com/filmow/filmow-api/vendor/github.com/nuveo/prest/adapters/postgres.Query(0xc450ad25f0, 0x4a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/shelfgit.com/filmow/filmow-api/vendor/github.com/nuveo/prest/adapters/postgres/postgres.go:260 +0xc1
```
![captura_de_tela_2017-03-16_a__s_19 32 42](https://cloud.githubusercontent.com/assets/31996/24021694/ec5e79c2-0a80-11e7-8ae5-681c726fdb42.jpg)

**Comment by avelino** [comment]
seems like memory leak
